spring:
  datasource:
    url: jdbc:postgresql://postgres_server:5432/reserva
    username: postgres
    password: 123456Ab
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
      generate-ddl: true
    show-sql: true